CREATE TABLE IF NOT EXISTS users
(
    id         UUID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fulll_name VARCHAR(255)                          NOT NULL,
    email      VARCHAR(512)                          NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS bookings
(
    id      UUID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment VARCHAR(512),
    CONSTRAINT pk_booking PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS conference_rooms
(
    id          UUID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                          NOT NULL,
    description VARCHAR(512)                          NOT NULL,
    CONSTRAINT pk_room PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS time_slots
(
    id         UUID GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start      TIMESTAMP WITHOUT TIME ZONE           NOT NULL,
    end        TIMESTAMP WITHOUT TIME ZONE           NOT NULL,
    avaliable  BOOLEAN,
    booking_id INTEGER REFERENCES items (id) ON DELETE CASCADE,
    room_id    INTEGER REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT pk_timeslot PRIMARY KEY (id)
    );

DELETE
from users;
DELETE
from bookings;
DELETE
FROM conference_rooms;
DELETE
FROM time_slots;

ALTER TABLE users
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE bookings
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE conference_rooms
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE time_slots
    ALTER COLUMN id RESTART WITH 1;